SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES
FROM REST_INFO R
HAVING FAVORITES >= ALL(
    SELECT FAVORITES
    FROM REST_INFO R2
    WHERE R.FOOD_TYPE = R2.FOOD_TYPE
    GROUP BY REST_ID, REST_NAME, FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC