-- 코드를 작성해주세요
SELECT ID,(CASE
          WHEN CLASS = 1 THEN "LOW"
          WHEN CLASS = 2 THEN "MEDIUM"
          WHEN CLASS = 3 THEN "HIGH"
          WHEN CLASS = 4 THEN "CRITICAL"
          END) AS COLONY_NAME
FROM (SELECT *, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY) AS CLASS
     FROM ECOLI_DATA) AS TEMP
ORDER BY ID