WITH RECURSIVE GENERATION AS (
    SELECT ID, PARENT_ID, 1 AS Gen
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GEN + 1 AS GEN
    FROM ECOLI_DATA E
    INNER JOIN GENERATION G ON E.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT,Gen AS GENERATION
FROM GENERATION
WHERE ID NOT IN (SELECT PARENT_ID FROM GENERATION WHERE PARENT_ID IS NOT NULL)
GROUP BY Gen