WITH MAX_SIZE AS(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR, (MS.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA E
JOIN MAX_SIZE MS
ON YEAR(E.DIFFERENTIATION_DATE) = MS.YEAR
ORDER BY YEAR, YEAR_DEV