SELECT SCORE, R.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM (
    SELECT EMP_NO, SCORE, RANK() OVER (ORDER BY SCORE DESC) R
        FROM (
        SELECT EMP_NO, SUM(SCORE) AS SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
    )S
) R
LEFT JOIN HR_EMPLOYEES E ON R.EMP_NO = E.EMP_NO
WHERE R.R = 1;