SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT F
WHERE CATEGORY IN ("과자","국","김치","식용유")
HAVING PRICE >= ALL (
SELECT F2.PRICE
FROM FOOD_PRODUCT F2
WHERE F.CATEGORY = F2.CATEGORY
GROUP BY F2.PRODUCT_ID,F2.PRODUCT_NAME,F2.CATEGORY
)
ORDER BY MAX_PRICE DESC