SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE, PRODUCT_NAME, RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) R
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
) F
WHERE F.R = 1
ORDER BY MAX_PRICE DESC





# WITH F AS(
# SELECT *
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ("과자","국","김치","식용유"))

# SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
# FROM F
# HAVING PRICE >= ALL (
# SELECT F2.PRICE
# FROM F F2
# WHERE F.CATEGORY = F2.CATEGORY
# GROUP BY F2.PRODUCT_ID,F2.PRODUCT_NAME,F2.CATEGORY
# )
# ORDER BY MAX_PRICE DESC