WITH FISH_INFO_DISTILLED AS (
    SELECT ID, FISH_TYPE,
        CASE 
            WHEN LENGTH < 10 THEN 10
            WHEN LENGTH IS NULL THEN 10
            ELSE LENGTH
        END LENGTH
    FROM FISH_INFO
),
STATS AS (
    SELECT COUNT(*) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, AVG(LENGTH) AVG_LENGTH, FISH_TYPE
    FROM FISH_INFO_DISTILLED
    GROUP BY FISH_TYPE
)

SELECT FISH_COUNT,MAX_LENGTH, FISH_TYPE
FROM STATS
WHERE AVG_LENGTH >= 33
ORDER BY FISH_TYPE ASC;